### ISSUE TITLE
error LNK2019: unresolved external symbol SecureZeroMemory

### ISSUE THREAD

**Issue by Flamaros** [Leandros/WindowsHModular#20]
SecureZeroMemory function is inlined in microsofts headers so WindowsHModular should also embed the implementation.

For details, SecureZeroMemory is a macro defined in WinBase.h (C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\WinBase.h):
```cpp
#define SecureZeroMemory RtlSecureZeroMemory
```

and RtlSecureZeroMemory is defined in winnt.h
```cpp
FORCEINLINE
PVOID
RtlSecureZeroMemory(
    _Out_writes_bytes_all_(cnt) PVOID ptr,
    _In_ SIZE_T cnt
    )
{
    volatile char *vptr = (volatile char *)ptr;

#if defined(_M_AMD64)

    __stosb((PBYTE )((DWORD64)vptr), 0, cnt);

#else

    while (cnt) {

#if !defined(_M_CEE) && (defined(_M_ARM) || defined(_M_ARM64))

        __iso_volatile_store8(vptr, 0);

#else

        *vptr = 0;

#endif

        vptr++;
        cnt--;
    }

#endif // _M_AMD64

    return ptr;
}
```

**Comment by Leandros** [comment]
Can you send a pull request with a fix?

**Comment by Flamaros** [comment]
I can do that, because I fixed it locally, but I am not really sure how to handle CPU architecture checks for implementation.
are _M_AMD64, _M_CEE,... correctly defined in WindowsHModular?

I think that I will found some other issues, as I am trying to write a compiler from scratch without libc, stl,... as dependencies.
