### ISSUE TITLE
VirtualAlloc and VirtualFree

### ISSUE THREAD

**Issue by jesta88** [Leandros/WindowsHModular#5]
These are my 2 most-used windows.h functions, so it would be great to have them!

**Comment by Leandros** [comment]
They're in `io.h`: https://github.com/Leandros/WindowsHModular/blob/353305c333c9738d2567a9f424b576438f1dc127/include/win32/io.h#L231-L252

We could move them into their own `memory.h`, as proposed in #6, but would have to include it in `io.h`, to avoid breaking existing code on upgrade.

**Comment by jesta88** [comment]
Crap, forget about it then. The Github search function couldn't find them in the repo, that's why I added them in memory.h. I'll close the issue and PR.
